export const pokemonData = [
  {
    id: 1,
    name: "Pikachu",
    types: ["Electric"],
    tier: "NU",
    generation: 1,
    fullyEvolved: false,
    isRegional: false,
    image: "/placeholder.svg?text=Pikachu",
  },
  {
    id: 2,
    name: "Charizard",
    types: ["Fire", "Flying"],
    tier: "OU",
    generation: 1,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Charizard",
  },
  {
    id: 3,
    name: "Blastoise",
    types: ["Water"],
    tier: "UU",
    generation: 1,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Blastoise",
  },
  {
    id: 4,
    name: "Venusaur",
    types: ["Grass", "Poison"],
    tier: "OU",
    generation: 1,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Venusaur",
  },
  {
    id: 5,
    name: "Mewtwo",
    types: ["Psychic"],
    tier: "Uber",
    generation: 1,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Mewtwo",
  },
  {
    id: 6,
    name: "Dragonite",
    types: ["Dragon", "Flying"],
    tier: "OU",
    generation: 1,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Dragonite",
  },
  {
    id: 7,
    name: "Tyranitar",
    types: ["Rock", "Dark"],
    tier: "OU",
    generation: 2,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Tyranitar",
  },
  {
    id: 8,
    name: "Lugia",
    types: ["Psychic", "Flying"],
    tier: "Uber",
    generation: 2,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Lugia",
  },
  {
    id: 9,
    name: "Scizor",
    types: ["Bug", "Steel"],
    tier: "OU",
    generation: 2,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Scizor",
  },
  {
    id: 10,
    name: "Blaziken",
    types: ["Fire", "Fighting"],
    tier: "Uber",
    generation: 3,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Blaziken",
  },
  {
    id: 11,
    name: "Salamence",
    types: ["Dragon", "Flying"],
    tier: "OU",
    generation: 3,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Salamence",
  },
  {
    id: 12,
    name: "Metagross",
    types: ["Steel", "Psychic"],
    tier: "OU",
    generation: 3,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Metagross",
  },
  {
    id: 13,
    name: "Garchomp",
    types: ["Dragon", "Ground"],
    tier: "OU",
    generation: 4,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Garchomp",
  },
  {
    id: 14,
    name: "Lucario",
    types: ["Fighting", "Steel"],
    tier: "OU",
    generation: 4,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Lucario",
  },
  {
    id: 15,
    name: "Togekiss",
    types: ["Fairy", "Flying"],
    tier: "UU",
    generation: 4,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Togekiss",
  },
  {
    id: 16,
    name: "Hydreigon",
    types: ["Dark", "Dragon"],
    tier: "UU",
    generation: 5,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Hydreigon",
  },
  {
    id: 17,
    name: "Volcarona",
    types: ["Bug", "Fire"],
    tier: "OU",
    generation: 5,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Volcarona",
  },
  {
    id: 18,
    name: "Greninja",
    types: ["Water", "Dark"],
    tier: "OU",
    generation: 6,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Greninja",
  },
  {
    id: 19,
    name: "Aegislash",
    types: ["Steel", "Ghost"],
    tier: "UU",
    generation: 6,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Aegislash",
  },
  {
    id: 20,
    name: "Mimikyu",
    types: ["Ghost", "Fairy"],
    tier: "UU",
    generation: 7,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Mimikyu",
  },
  {
    id: 21,
    name: "Toxapex",
    types: ["Poison", "Water"],
    tier: "OU",
    generation: 7,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Toxapex",
  },
  {
    id: 22,
    name: "Dragapult",
    types: ["Dragon", "Ghost"],
    tier: "OU",
    generation: 8,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Dragapult",
  },
  {
    id: 23,
    name: "Urshifu",
    types: ["Fighting", "Dark"],
    tier: "OU",
    generation: 8,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Urshifu",
  },
  {
    id: 24,
    name: "Miraidon",
    types: ["Electric", "Dragon"],
    tier: "Uber",
    generation: 9,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Miraidon",
  },
  {
    id: 25,
    name: "Koraidon",
    types: ["Fighting", "Dragon"],
    tier: "Uber",
    generation: 9,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Koraidon",
  },
  {
    id: 26,
    name: "Alolan Ninetales",
    types: ["Ice", "Fairy"],
    tier: "UU",
    generation: 7,
    fullyEvolved: true,
    isRegional: true,
    image: "/placeholder.svg?text=A-Ninetales",
  },
  {
    id: 27,
    name: "Galarian Darmanitan",
    types: ["Ice"],
    tier: "OU",
    generation: 8,
    fullyEvolved: true,
    isRegional: true,
    image: "/placeholder.svg?text=G-Darmanitan",
  },
  {
    id: 28,
    name: "Hisuian Zoroark",
    types: ["Normal", "Ghost"],
    tier: "UU",
    generation: 8,
    fullyEvolved: true,
    isRegional: true,
    image: "/placeholder.svg?text=H-Zoroark",
  },
  {
    id: 29,
    name: "Paldean Tauros",
    types: ["Fighting"],
    tier: "RU",
    generation: 9,
    fullyEvolved: true,
    isRegional: true,
    image: "/placeholder.svg?text=P-Tauros",
  },
  {
    id: 30,
    name: "Charjabug",
    types: ["Bug", "Electric"],
    tier: "NU",
    generation: 7,
    fullyEvolved: false,
    isRegional: false,
    image: "/placeholder.svg?text=Charjabug",
  },
  {
    id: 31,
    name: "Drizzile",
    types: ["Water"],
    tier: "LC",
    generation: 8,
    fullyEvolved: false,
    isRegional: false,
    image: "/placeholder.svg?text=Drizzile",
  },
  {
    id: 32,
    name: "Ivysaur",
    types: ["Grass", "Poison"],
    tier: "NFE",
    generation: 1,
    fullyEvolved: false,
    isRegional: false,
    image: "/placeholder.svg?text=Ivysaur",
  },
  {
    id: 33,
    name: "Wartortle",
    types: ["Water"],
    tier: "NFE",
    generation: 1,
    fullyEvolved: false,
    isRegional: false,
    image: "/placeholder.svg?text=Wartortle",
  },
  {
    id: 34,
    name: "Grovyle",
    types: ["Grass"],
    tier: "NFE",
    generation: 3,
    fullyEvolved: false,
    isRegional: false,
    image: "/placeholder.svg?text=Grovyle",
  },
  {
    id: 35,
    name: "Haunter",
    types: ["Ghost", "Poison"],
    tier: "NFE",
    generation: 1,
    fullyEvolved: false,
    isRegional: false,
    image: "/placeholder.svg?text=Haunter",
  },
  {
    id: 36,
    name: "Magneton",
    types: ["Electric", "Steel"],
    tier: "NU",
    generation: 1,
    fullyEvolved: false,
    isRegional: false,
    image: "/placeholder.svg?text=Magneton",
  },
  {
    id: 37,
    name: "Porygon2",
    types: ["Normal"],
    tier: "RU",
    generation: 2,
    fullyEvolved: false,
    isRegional: false,
    image: "/placeholder.svg?text=Porygon2",
  },
  {
    id: 38,
    name: "Chansey",
    types: ["Normal"],
    tier: "UU",
    generation: 1,
    fullyEvolved: false,
    isRegional: false,
    image: "/placeholder.svg?text=Chansey",
  },
  {
    id: 39,
    name: "Scyther",
    types: ["Bug", "Flying"],
    tier: "RU",
    generation: 1,
    fullyEvolved: false,
    isRegional: false,
    image: "/placeholder.svg?text=Scyther",
  },
  {
    id: 40,
    name: "Pawmot",
    types: ["Electric", "Fighting"],
    tier: "RU",
    generation: 9,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Pawmot",
  },
  {
    id: 41,
    name: "Ceruledge",
    types: ["Fire", "Ghost"],
    tier: "OU",
    generation: 9,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Ceruledge",
  },
  {
    id: 42,
    name: "Kingambit",
    types: ["Dark", "Steel"],
    tier: "OU",
    generation: 9,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Kingambit",
  },
  {
    id: 43,
    name: "Gholdengo",
    types: ["Steel", "Ghost"],
    tier: "OU",
    generation: 9,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Gholdengo",
  },
  {
    id: 44,
    name: "Tinkaton",
    types: ["Fairy", "Steel"],
    tier: "RU",
    generation: 9,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Tinkaton",
  },
  {
    id: 45,
    name: "Garganacl",
    types: ["Rock"],
    tier: "OU",
    generation: 9,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Garganacl",
  },
  {
    id: 46,
    name: "Armarouge",
    types: ["Fire", "Psychic"],
    tier: "UU",
    generation: 9,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Armarouge",
  },
  {
    id: 47,
    name: "Espathra",
    types: ["Psychic"],
    tier: "OU",
    generation: 9,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Espathra",
  },
  {
    id: 48,
    name: "Palafin",
    types: ["Water"],
    tier: "OU",
    generation: 9,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Palafin",
  },
  {
    id: 49,
    name: "Annihilape",
    types: ["Fighting", "Ghost"],
    tier: "OU",
    generation: 9,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Annihilape",
  },
  {
    id: 50,
    name: "Baxcalibur",
    types: ["Dragon", "Ice"],
    tier: "OU",
    generation: 9,
    fullyEvolved: true,
    isRegional: false,
    image: "/placeholder.svg?text=Baxcalibur",
  },
]
